# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
    displayName: 'Install NG'

  - script: |
      cd flex-demo
      npm install
    displayName: 'npm install'

  - script: |
      cd flex-demo
      ng build --prod
    displayName: 'npm build'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)/flex-demo/dist/flex-demo'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/flex-demo/dist/flex-demo'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/flex-demo$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: app'
    inputs:
      ArtifactName: app
